owner: H-edu-dev
repo: upptime

sites:
  - name: Homepage
    url: https://h-edu.cz
    __dangerous__body_degraded_if_text_missing: "Přihlásit se"
    maxResponseTime: 5000

  - name: API Next
    url: https://api-next.h-edu.cz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 404

  - name: API Old
    url: https://api2.h-edu.cz
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 404

  - name: Test Homepage
    url: https://test.h-edu.cz
    __dangerous__body_degraded_if_text_missing: "Přihlásit se"

  - name: Test API Next
    url: https://api-next-test.h-edu.cz
    expectedStatusCodes:
      - 200
      - 404

  - name: Test API Old
    url: https://api2-test.h-edu.cz
    expectedStatusCodes:
      - 200
      - 404


status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: H-edu uptime guard
  introTitle: "Monitoring dostupnosti **H-edu** služeb"
  introMessage: ""
  # light, dark, night or ocean
  theme: light
  navbar:
    - title: Homepage
      href: https://h-edu.cz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
